name: Build and Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

# Define common setup steps template
.common_steps: &common_steps
  - name: Checkout code
    uses: actions/checkout@v4
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '18.20.5'
      cache: 'yarn'
  - name: Install dependencies
    run: |
      yarn install --frozen-lockfile
      yarn install --cwd sample --frozen-lockfile
  - name: Inject env file
    run: |
      echo "export const APP_ID = 'app_id';" >> sample/src/env.ts
      echo "export const INITIAL_ROUTE = 'route';" >> sample/src/env.ts

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      <<: *common_steps
      - name: Run linting
        run: yarn lint

  typescript:
    runs-on: ubuntu-latest
    steps:
      <<: *common_steps
      - name: TypeScript check
        run: yarn typescript

  sample-typescript:
    runs-on: ubuntu-latest
    steps:
      <<: *common_steps
      - name: Sample TypeScript check
        run: yarn sample:tsc

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      <<: *common_steps
      - name: Run unit tests
        run: yarn test --coverage
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  build-package:
    runs-on: ubuntu-latest
    steps:
      <<: *common_steps
      - name: Build package
        run: yarn build